# Generated by Django 5.2.17 on 2026-10-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.DateField(help_text='First day of the month this snapshot covers.')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('new_mrr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('expansion_mrr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('contraction_mrr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('churned_mrr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active_customers', models.PositiveIntegerField(default=0)),
                ('new_customers', models.PositiveIntegerField(default=0)),
                ('churned_customers', models.PositiveIntegerField(default=0)),
                ('trials_started', models.PositiveIntegerField(default=0)),
                ('trials_converted', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='accounts.organization')),
            ],
            options={
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'month'), name='unique_snapshot_month')],
            },
        ),
    ]
