# Generated by Django 5.2.17 on 2026-10-04 14:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=80)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('company_size', models.CharField(choices=[('1-10', '1–10'), ('11-50', '11–50'), ('51-200', '51–200'), ('201-1000', '201–1,000'), ('1000+', '1,000+')], default='11-50', max_length=10)),
                ('channel', models.CharField(choices=[('organic', 'Organic search'), ('paid', 'Paid ads'), ('referral', 'Referral'), ('partner', 'Partner'), ('outbound', 'Outbound sales')], default='organic', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past due'), ('churned', 'Churned')], default='trialing', max_length=20)),
                ('joined_at', models.DateField()),
                ('churned_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.organization')),
            ],
            options={
                'ordering': ['-joined_at', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('features', models.JSONField(blank=True, default=list)),
                ('trial_days', models.PositiveSmallIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.organization')),
            ],
            options={
                'ordering': ['sort_order', 'monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='trialing', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mrr', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('started_at', models.DateField()),
                ('trial_ends_at', models.DateField(blank=True, null=True)),
                ('activated_at', models.DateField(blank=True, null=True)),
                ('cancelled_at', models.DateField(blank=True, null=True)),
                ('current_period_end', models.DateField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=120)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='billing.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='accounts.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='subscriptions', to='billing.plan')),
                ('previous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor', to='billing.subscription')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='paid', max_length=20)),
                ('method', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('paypal', 'PayPal')], default='card', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('occurred_at', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='billing.subscription')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'status'], name='billing_cus_organiz_3c6ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['organization', 'joined_at'], name='billing_cus_organiz_7cfcd2_idx'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='unique_customer_email'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_plan_slug'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'status'], name='billing_sub_organiz_e1331c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'activated_at'], name='billing_sub_organiz_51087b_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'cancelled_at'], name='billing_sub_organiz_c8686b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'occurred_at'], name='billing_tra_organiz_2454c1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['organization', 'status'], name='billing_tra_organiz_f3fa39_idx'),
        ),
    ]
